# Generated by Django 2.1.1 on 2018-10-03 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('delivery', models.CharField(choices=[('', ''), ('DONOR', 'Levar pessoalmente'), ('SCHOOL', 'Quero que retirem')], max_length=255)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, choices=[('', ''), ('AVERAGE', 'Regular'), ('GOOD', 'Bom'), ('VERY_GOOD', 'Muito Bom')], max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donation.Donation')),
            ],
            options={
                'verbose_name': 'Item para Doação',
                'verbose_name_plural': 'Itens para Doação',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('category', models.CharField(choices=[('', 'selecionar a categoria'), ('SPORTING_GOODS', 'Materiais Esportivos'), ('CLOTHING', 'Vestuário'), ('BOOKS', 'Livros')], max_length=255, verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Esporte',
                'verbose_name_plural': 'Esportes',
            },
        ),
        migrations.AddField(
            model_name='donationitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donation.Material'),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donation.Sport', verbose_name='Esporte'),
        ),
    ]
