# Generated by Django 2.1.1 on 2018-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='delivery',
            field=models.CharField(choices=[('', 'forma de entrega'), ('DONOR', 'Levar pessoalmente'), ('SCHOOL', 'Quero que retirem')], max_length=255),
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='condition',
            field=models.CharField(blank=True, choices=[('', 'selecione a condição do material'), ('AVERAGE', 'Regular'), ('GOOD', 'Bom'), ('VERY_GOOD', 'Muito Bom')], max_length=255, null=True),
        ),
    ]
