# Generated by Django 2.1.1 on 2018-10-14 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20181005_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='delivery',
            field=models.CharField(choices=[('', 'forma de entrega'), ('DONOR', 'Levar pessoalmente'), ('SCHOOL', 'Quero que retirem')], max_length=255, verbose_name='Forma de entrega'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor', to=settings.AUTH_USER_MODEL, verbose_name='Doador'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to=settings.AUTH_USER_MODEL, verbose_name='Escola'),
        ),
    ]
