# Generated by Django 2.1.1 on 2018-10-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20181014_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donation.Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('', 'selecionar a categoria'), ('SPORTING_GOODS', 'Materiais Esportivos'), ('BOOKS', 'Livros'), ('COMPUTER_EQUIPMENT', 'Equipamentos de informática'), ('TOYS', 'Brinquedos')], max_length=255, verbose_name='Categoria'),
        ),
    ]
