# Generated by Django 2.1.1 on 2018-12-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_donationitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='delivery',
            field=models.CharField(choices=[('', 'Forma de entrega'), ('DONOR', 'Levar pessoalmente'), ('SCHOOL', 'Quero que retirem')], max_length=255, verbose_name='Forma de entrega'),
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='category',
            field=models.CharField(choices=[('', 'Selecione a categoria'), ('SPORTING_GOODS', 'Materiais Esportivos'), ('BOOKS', 'Livros'), ('COMPUTER_EQUIPMENT', 'Equipamentos de Informática')], max_length=255, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='condition',
            field=models.CharField(blank=True, choices=[('', 'Selecione a condição do material'), ('AVERAGE', 'Regular'), ('GOOD', 'Bom'), ('VERY_GOOD', 'Muito Bom')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('', 'Selecione a categoria'), ('SPORTING_GOODS', 'Materiais Esportivos'), ('BOOKS', 'Livros'), ('COMPUTER_EQUIPMENT', 'Equipamentos de Informática')], max_length=255, verbose_name='Categoria'),
        ),
    ]
