# Generated by Django 2.1.1 on 2019-02-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_auto_20190131_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=None, related_name='sport', to='donation.Sport'),
        ),
    ]
