# Generated by Django 2.1.1 on 2019-02-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_material_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
