# Generated by Django 2.1.1 on 2018-12-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_user_social_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
